import { Prisma, PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  const password1 = (await bcrypt.hash('password', 10)) as string;
  const password2 = (await bcrypt.hash('password', 10)) as string;

  await prisma.admin.createMany({
    data: [
      { username: 'admin', password: password1, role: 'REVIEWER' },
      { username: 'john_doe', password: password2, role: 'REVIEWER' },
    ],
    skipDuplicates: true,
  });

  for (const proposal of dummyProposals) {
    await prisma.proposal.create({
      data: proposal as unknown as Prisma.ProposalCreateInput,
    });
  }
}

main()
  .then(() => console.log('Seed complete'))
  .catch((e) => console.error(e))
  .finally(() => prisma.$disconnect());

const dummyProposals = [
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Solar Water Pumps',
    organization: 'Zambia Green Energy Ltd',
    contactPerson: 'Ms Chileshe',
    location: 'Zambia',
    sector: 'Renewable Energy',
    startDate: '2025-01-15T00:00:00.000Z',
    endDate: '2030-12-31T00:00:00.000Z',
    stage: 'Feasibility',
    estimatedInvestment: 50000,
    currency: 'USD',
    partners: 'Zambia Agricultural Development Agency',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: [
      'Renewable Energy',
      'Water & Waste Management',
      'Climate Adaptation & Resilience',
    ],
    categoriesOther: '',
    envImpact: [
      'GHG emissions reduction (mitigation)',
      'Resource efficiency & circular economy',
    ],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Positive impact expected on rural water access and emissions reduction',
    socialImpact: ['Job creation', 'Community well-being / social inclusion'],
    socialImpactDescription:
      'Significant local employment and access to water resources',
    compliance: {
      'Compliant with national laws?': 'Not Done',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 60000,
    fundingSought: ['Grant', 'Equity', 'Senior loan'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: {
      key: 'proposals/1760400707976-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707976-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    businessPlan: {
      key: 'proposals/1760400708111-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708111-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    financialStatements: {
      key: 'proposals/1760400708208-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708208-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    partnerships: {
      key: 'proposals/1760400708309-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708309-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    techStudies: {
      key: 'proposals/1760400708409-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708409-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    other: {
      key: 'proposals/1760400708511-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708511-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    signedName: 'Lwazi Banda',
    position: 'Project Manager',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Community Irrigation Systems',
    organization: 'Zambia Agro Solutions',
    contactPerson: 'Mr Tembo',
    location: 'Zambia',
    sector: 'Sustainable Agriculture & Food Systems / Forestry',
    startDate: '2025-03-01T00:00:00.000Z',
    endDate: '2032-12-31T00:00:00.000Z',
    stage: 'Early Stage',
    estimatedInvestment: 35000,
    currency: 'USD',
    partners: 'Zambia Rural Development Trust',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: [
      'Sustainable Agriculture & Food Systems / Forestry',
      'Water & Waste Management',
    ],
    categoriesOther: '',
    envImpact: [
      'GHG emissions reduction (mitigation)',
      'Biodiversity protection/enhancement',
    ],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Improves irrigation efficiency and reduces environmental impact',
    socialImpact: ['Job creation', 'Community well-being / social inclusion'],
    socialImpactDescription:
      'Supports rural livelihoods and smallholder farmers',
    compliance: {
      'Compliant with national laws?': 'Not Applicable',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 45000,
    fundingSought: ['Grant', 'Subordinated loan', 'Reimbursable grant'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: {
      key: 'proposals/1760400707976-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707976-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    businessPlan: {
      key: 'proposals/1760400708111-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708111-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    financialStatements: null,
    partnerships: null,
    techStudies: {
      key: 'proposals/1760400708409-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708409-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    other: null,
    signedName: 'Chanda Mwansa',
    position: 'Project Lead',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Urban Green Spaces',
    organization: 'Zambia Eco Urban Ltd',
    contactPerson: 'Ms Phiri',
    location: 'Zambia',
    sector: 'Biodiversity & Ecosystem Services',
    startDate: '2025-06-01T00:00:00.000Z',
    endDate: '2035-05-31T00:00:00.000Z',
    stage: 'Development',
    estimatedInvestment: 80000,
    currency: 'USD',
    partners: 'Lusaka City Council',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: [
      'Biodiversity & Ecosystem Services',
      'Green Buildings',
      'Social Co-Benefits',
    ],
    categoriesOther: '',
    envImpact: [
      'Biodiversity protection/enhancement',
      'Pollution prevention/control',
    ],
    envImpactIndicator: 'Targets',
    envImpactDescription: 'Enhances urban biodiversity and reduces pollution',
    socialImpact: ['Community well-being / social inclusion', 'Job creation'],
    socialImpactDescription: 'Creates recreational spaces and local employment',
    compliance: {
      'Compliant with national laws?': 'Not Applicable',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 100000,
    fundingSought: ['Grant', 'Senior loan', 'Equity'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: {
      key: 'proposals/1760400707976-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707976-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    businessPlan: null,
    financialStatements: null,
    partnerships: {
      key: 'proposals/1760400708309-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708309-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    techStudies: null,
    other: null,
    signedName: 'Mwila Kunda',
    position: 'Urban Planner',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Rural Solar Mini-Grids',
    organization: 'Zambia Energy Access',
    contactPerson: 'Mr Mwewa',
    location: 'Zambia',
    sector: 'Renewable Energy',
    startDate: '2025-08-01T00:00:00.000Z',
    endDate: '2033-07-31T00:00:00.000Z',
    stage: 'Ready to Implement',
    estimatedInvestment: 120000,
    currency: 'USD',
    partners: 'Zambia Rural Electrification Authority',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: ['Renewable Energy', 'Climate Adaptation & Resilience'],
    envImpact: [
      'GHG emissions reduction (mitigation)',
      'Resource efficiency & circular economy',
    ],
    categoriesOther: '',
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Reduces emissions by providing clean electricity to rural communities',
    socialImpact: ['Job creation', 'Community well-being / social inclusion'],
    socialImpactDescription: 'Improves energy access and creates local jobs',
    compliance: {
      'Compliant with national laws?': 'Not Applicable',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 150000,
    fundingSought: ['Grant', 'Equity', 'Senior loan'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: null,
    businessPlan: null,
    financialStatements: null,
    partnerships: {
      key: 'proposals/1760400708309-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708309-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    techStudies: null,
    other: null,
    signedName: 'Nchimunya Phiri',
    position: 'Energy Project Coordinator',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Mangrove Restoration in Lake Tanganyika Basin',
    organization: 'Zambia Coastal Conservation',
    contactPerson: 'Ms Lungu',
    location: 'Zambia',
    sector: 'Biodiversity & Ecosystem Services',
    startDate: '2025-04-01T00:00:00.000Z',
    endDate: '2030-03-31T00:00:00.000Z',
    stage: 'Concept',
    estimatedInvestment: 40000,
    currency: 'USD',
    partners: 'WWF Zambia',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: [
      'Biodiversity & Ecosystem Services',
      'Climate Adaptation & Resilience',
    ],
    categoriesOther: '',
    envImpact: [
      'Biodiversity protection/enhancement',
      'Climate change adaptation',
    ],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Restores mangroves to protect biodiversity and local climate resilience',
    socialImpact: ['Job creation', 'Community well-being / social inclusion'],
    socialImpactDescription:
      'Generates local employment and strengthens community resilience',
    compliance: {
      'Compliant with national laws?': 'Not Applicable',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 50000,
    fundingSought: ['Grant', 'Equity'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: null,
    businessPlan: null,
    financialStatements: null,
    partnerships: null,
    techStudies: null,
    other: null,
    signedName: 'Josephine Mwape',
    position: 'Project Coordinator',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Off-Grid Solar Lighting for Rural Schools',
    organization: 'Zambia EduSolar',
    contactPerson: 'Mr Musonda',
    location: 'Zambia',
    sector: 'Renewable Energy',
    startDate: '2025-09-01T00:00:00.000Z',
    endDate: '2032-08-31T00:00:00.000Z',
    stage: 'Expansion',
    estimatedInvestment: 90000,
    currency: 'USD',
    partners: 'Ministry of Education Zambia',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: ['Renewable Energy', 'Social Co-Benefits'],
    categoriesOther: '',
    envImpact: ['GHG emissions reduction (mitigation)'],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Reduces reliance on kerosene lamps, cutting emissions',
    socialImpact: ['Community well-being / social inclusion', 'Job creation'],
    socialImpactDescription:
      'Improves learning conditions and provides local jobs',
    compliance: {
      'Compliant with national laws?': 'Done',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 100000,
    fundingSought: ['Grant', 'Senior loan'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: {
      key: 'proposals/1760400707976-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707976-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    businessPlan: null,
    financialStatements: null,
    partnerships: null,
    techStudies: null,
    other: null,
    signedName: 'Patrick Tembo',
    position: 'Project Manager',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Rainwater Harvesting for Rural Schools',
    organization: 'Zambia Water Solutions',
    contactPerson: 'Ms Mwila',
    location: 'Zambia',
    sector: 'Water & Waste Management',
    startDate: '2025-05-01T00:00:00.000Z',
    endDate: '2031-04-30T00:00:00.000Z',
    stage: 'Development',
    estimatedInvestment: 60000,
    currency: 'USD',
    partners: 'Ministry of Education Zambia',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: ['Water & Waste Management', 'Climate Adaptation & Resilience'],
    categoriesOther: '',
    envImpact: [
      'Resource efficiency & circular economy',
      'Pollution prevention/control',
    ],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Harvesting rainwater reduces dependency on unsafe water sources',
    socialImpact: ['Community well-being / social inclusion', 'Job creation'],
    socialImpactDescription:
      'Improves school access to safe water and creates local employment',
    compliance: {
      'Compliant with national laws?': 'Done',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Applicable',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 75000,
    fundingSought: ['Grant', 'Subordinated loan', 'Reimbursable grant'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: null,
    businessPlan: null,
    financialStatements: null,
    partnerships: {
      key: 'proposals/1760400708309-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400708309-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    techStudies: null,
    other: null,
    signedName: 'Beatrice Phiri',
    position: 'Project Coordinator',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Zambia Agroforestry Initiative',
    organization: 'Zambia Green Farms',
    contactPerson: 'Mr Chanda',
    location: 'Zambia',
    sector: 'Sustainable Agriculture & Food Systems / Forestry',
    startDate: '2025-02-01T00:00:00.000Z',
    endDate: '2032-01-31T00:00:00.000Z',
    stage: 'Early Stage',
    estimatedInvestment: 70000,
    currency: 'USD',
    partners: 'Zambia Agricultural Development Agency',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: [
      'Sustainable Agriculture & Food Systems / Forestry',
      'Climate Adaptation & Resilience',
    ],
    categoriesOther: '',
    envImpact: [
      'GHG emissions reduction (mitigation)',
      'Biodiversity protection/enhancement',
    ],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Combines tree planting with sustainable crop production',
    socialImpact: ['Job creation', 'Community well-being / social inclusion'],
    socialImpactDescription:
      'Creates local employment and strengthens rural livelihoods',
    compliance: {
      'Compliant with national laws?': 'Done',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Applicable',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 90000,
    fundingSought: ['Grant', 'Equity'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: null,
    businessPlan: null,
    financialStatements: null,
    partnerships: null,
    techStudies: null,
    other: null,
    signedName: 'Charles Mwape',
    position: 'Project Lead',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Zambia Eco-Tourism Development',
    organization: 'Zambia Tourism & Conservation',
    contactPerson: 'Ms Luyando',
    location: 'Zambia',
    sector: 'Biodiversity & Ecosystem Services',
    startDate: '2025-07-01T00:00:00.000Z',
    endDate: '2035-06-30T00:00:00.000Z',
    stage: 'Operational',
    estimatedInvestment: 150000,
    currency: 'USD',
    partners: 'Zambia Wildlife Authority',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: ['Biodiversity & Ecosystem Services', 'Social Co-Benefits'],
    categoriesOther: '',
    envImpact: ['Biodiversity protection/enhancement'],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Promotes conservation and protection of wildlife habitats',
    socialImpact: ['Job creation', 'Community well-being / social inclusion'],
    socialImpactDescription: 'Generates tourism income and local employment',
    compliance: {
      'Compliant with national laws?': 'Done',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Done',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 200000,
    fundingSought: ['Grant', 'Senior loan', 'Equity'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: {
      key: 'proposals/1760400707976-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707976-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    businessPlan: null,
    financialStatements: null,
    partnerships: null,
    techStudies: null,
    other: null,
    signedName: 'Lillian Phiri',
    position: 'Project Manager',
    comments: null,
  },
  {
    proposalStatus: 'PENDING',
    projectTitle: 'Rural Health Clinic Solar Electrification',
    organization: 'Zambia Health Energy',
    contactPerson: 'Mr Banda',
    location: 'Zambia',
    sector: 'Renewable Energy',
    startDate: '2025-03-15T00:00:00.000Z',
    endDate: '2032-03-14T00:00:00.000Z',
    stage: 'Feasibility',
    estimatedInvestment: 80000,
    currency: 'USD',
    partners: 'Ministry of Health Zambia',
    projectOverview: {
      key: 'proposals/1760400707686-TEST PDF.pdf',
      url: 'https://undp-files-bucket.s3.eu-west-2.amazonaws.com/proposals/1760400707686-TEST PDF.pdf',
      size: 11266,
      mimetype: 'application/pdf',
      originalName: 'TEST PDF.pdf',
    },
    categories: ['Renewable Energy', 'Social Co-Benefits'],
    categoriesOther: '',
    envImpact: ['GHG emissions reduction (mitigation)'],
    envImpactIndicator: 'Targets',
    envImpactDescription:
      'Provides clean electricity, reducing diesel generator use',
    socialImpact: ['Community well-being / social inclusion'],
    socialImpactDescription: 'Improves rural healthcare services',
    compliance: {
      'Compliant with national laws?': 'Done',
      'Legally registered in Zambia?': 'Done',
      'Climate risk screening completed?': 'Not Done',
      'Do No Significant Harm Principle met?': 'Not Done',
      'Environmental and Social Impact Assessment (ESIA) conducted?':
        'Not Done',
      'No adverse impacts on critical habitats, indigenous communities, cultural heritage?':
        'Not Applicable',
    },
    fundingOptions: {
      'Any Co-financing secured?': 'No',
      'No Estimated IRR / ROI available?': 'Yes',
      'Feasibility Study / Business Plan Developed?': 'Yes',
    },
    fundingOptionsOther: '',
    totalCost: 90000,
    fundingSought: ['Grant', 'Subordinated loan'],
    scalable: 'Yes',
    measureableImpact: true,
    annualReporting: true,
    keyIndicators: true,
    monitoring: true,
    companyRegistration: null,
    businessPlan: null,
    financialStatements: null,
    partnerships: null,
    techStudies: null,
    other: null,
    signedName: 'George Tembo',
    position: 'Project Coordinator',
    comments: null,
  },
];
